from pathlib import Path
import ast, json
import pandas as pd
from minimal_pipeline import load_inputs
from parity_evaluators import eval_A, deadline_A, sweep

ROOT=Path(__file__).resolve().parents[1]; TOL=1e-6
def main():
 d=load_inputs(); boxes={str(x['货箱编号']):x for x in d['boxes']}; s=pd.read_csv(ROOT/'checkpoint_best_feasible_11/schedule.csv'); t,dl,e=eval_A(s,d)
 # Q2 primary table
 cert=pd.read_csv(ROOT/'results/final_q3_continuous_certification.csv'); relay_energy=sum(float(d['relay']['power_kw'])*float(x.total_distance_m)/float(d['relay']['speed'])/3600.0 for _,x in cert.iterrows() if bool(x.relay_needed) and bool(x.relay_feasible))
 metrics={'sorties':len(s),'late_boxes':int((dl.lateness> TOL).sum()),'late_sorties':int(t.late_flag.sum()),'total_lateness_s':float(dl.lateness.sum()),'max_lateness_s':float(dl.lateness.max()),'makespan_s':float(s.return_s.max()),'transport_flight_energy_kwh':float(s.energy_kwh.sum()),'relay_energy_kwh':relay_energy,'total_energy_kwh':float(s.energy_kwh.sum())+relay_energy,'avg_boxes_per_sortie':float(s.box_ids.map(lambda x:len(ast.literal_eval(str(x)))).mean()),'max_boxes_per_sortie':int(s.box_ids.map(lambda x:len(ast.literal_eval(str(x)))).max()),'B_sorties':int((s.type=='B').sum()),'C_sorties':int((s.type=='C').sum()),'status':'BEST_KNOWN_FEASIBLE_NOT_PROVEN_OPTIMAL'}
 pd.DataFrame([metrics]).to_csv(ROOT/'results/q2_main_metrics.csv',index=False)
 # loading and split reasons
 rows=[]
 for _,r in s.iterrows():
  ids=ast.literal_eval(str(r.box_ids)); br=[boxes[x] for x in ids]; typ=d['drones'][r.type]; mass=sum(float(x['单箱质量（kg）']) for x in br); vol=sum(float(x['单箱体积（m³）']) for x in br); service=r.service; allr=[x for x in d['boxes'] if x['服务区编号']==service]; totalm=sum(float(x['单箱质量（kg）']) for x in allr); totalv=sum(float(x['单箱体积（m³）']) for x in allr); split_mass=totalm>typ.max_mass; split_vol=totalv>typ.volume
  ccap=d['drones']['C']; rows.append({'sortie_id':r.sortie,'service':service,'box_count':len(ids),'mass_kg':mass,'mass_capacity_kg':typ.max_mass,'mass_utilization':mass/typ.max_mass,'volume_m3':vol,'volume_capacity_m3':typ.volume,'volume_utilization':vol/typ.volume,'aircraft_type':r.type,'split_service_total_mass_kg':totalm,'split_service_total_volume_m3':totalv,'service_split_due_to_weight':totalm>ccap.max_mass,'service_split_due_to_volume':totalv>ccap.volume,'selected_type_exceeds_weight':split_mass,'selected_type_exceeds_volume':split_vol,'split_due_to_deadline':False})
 load=pd.DataFrame(rows); load.to_csv(ROOT/'results/q2_sortie_loading_analysis.csv',index=False)
 # comparison with frozen 60-second baseline, independently recomputed
 g=pd.read_csv(ROOT/'results/golden_grid60_schedule.csv'); gt,gd,ge=eval_A(g,d); base={'方案':'B_60s及时性优先基线','sorties':len(g),'late_boxes':int((gd.lateness>TOL).sum()),'late_sorties':int(gt.late_flag.sum()),'total_lateness_s':float(gd.lateness.sum()),'max_lateness_s':float(gd.lateness.max()),'makespan_s':float(g.return_s.max()),'total_energy_kwh':float(g.energy_kwh.sum())+relay_energy,'status':'60s baseline'}; cur={'方案':'A_连续时间当前best-known','sorties':metrics['sorties'],'late_boxes':metrics['late_boxes'],'late_sorties':metrics['late_sorties'],'total_lateness_s':metrics['total_lateness_s'],'max_lateness_s':metrics['max_lateness_s'],'makespan_s':metrics['makespan_s'],'total_energy_kwh':metrics['total_energy_kwh'],'status':metrics['status']}; pd.DataFrame([cur,base]).to_csv(ROOT/'results/q2_tradeoff_comparison.csv',index=False)
 split=load[load.service.isin(['S001','S002','S003'])].groupby('service').size().to_dict(); summary=f'''# Q2 final answer summary\n\n- Current schedule: **18 sorties**, all are single-point round trips.\n- It visits **15 service areas**; S001, S002 and S003 are each split into two sorties.\n- Independent audit: **11 late boxes and 6 late sorties**.\n- Makespan (last return): **{metrics['makespan_s']:.6f} s**.\n- Transport flight energy: **{metrics['transport_flight_energy_kwh']:.6f} kWh**; relay energy: **{metrics['relay_energy_kwh']:.6f} kWh**; total energy: **{metrics['total_energy_kwh']:.2f} kWh**.\n- Resource capacity audit: passed for transport, relay, B/C batteries and per-service resources.\n- Status: **BEST_KNOWN_FEASIBLE_NOT_PROVEN_OPTIMAL**.\n\n## Splitting explanation\n\nS001 has 154 kg and 0.394 m³ total demand, exceeding the maximum C-type payload and volume. S002 and S003 each have 81 kg, exceeding the C-type 80 kg payload while their 0.211 m³ volume does not exceed the C-type 0.25 m³ volume. Their split is therefore driven primarily by payload feasibility, not multi-point routing.\n\n## Trade-off\n\nCompared with the 60-second baseline, the current schedule reduces late boxes from 14 to 11 and late sorties from 7 to 6, but has larger total lateness, maximum lateness and makespan. Both schedules have 18 single-point sorties, so this is a timing/resource scheduling trade-off rather than a strict Pareto comparison.\n'''; (ROOT/'logs/q2_final_answer_summary.md').write_text(summary,encoding='utf-8')
 print(json.dumps(metrics,ensure_ascii=False,indent=2))
if __name__=='__main__': main()
